apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      hostNetwork: true  # Ensure it uses the host network
      containers:
        - name: react-container
          image: node:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              npm install -g npm@10.9.0 && \
              npm install -g create-react-app && \
              npx create-react-app /app && \
              cd /app && \
              npm start --host 0.0.0.0 --port 80  # Serve the app on port 80
          ports:
            - containerPort: 80  # Changed to 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: react-volume
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure the pod runs on slave2
      volumes:
        - emptyDir: {}
          name: react-volume
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: node-js
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80        # External HTTP port
      targetPort: 80  # Target port inside the container
      nodePort: 32000   # NodePort for host access

