apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure it runs on slave2
      volumes:
        - name: react-volume
          persistentVolumeClaim:
            claimName: react-app-pvc
      initContainers:
        - name: init-app
          image: 'busybox'
          command:
            - /bin/sh
            - '-c'
            - |
              if [ ! -d /app/node_modules ]; then
                echo "Installing dependencies...";
                cd /app && npm install;
              fi
          volumeMounts:
            - mountPath: /app
              name: react-volume
      containers:
        - name: react-container
          image: 'node:latest'
          imagePullPolicy: Always
          command:
            - /bin/sh
            - '-c'
          args:
            - |
              cd /app && \
              if [ ! -f package.json ]; then \
                echo "No project found, creating a new React app..."; \
                npx create-react-app .; \
              fi && \
              npm start --host 0.0.0.0 --port 80  # Start the app on port 80
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: react-volume
      restartPolicy: Always
