apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: 'node:latest'
          ports:
            - containerPort: 3000
          command: ["/bin/sh", "-c"]
          args: ["npm start"]
          volumeMounts:
            - name: react-volume
              mountPath: /app
      volumes:
        - name: react-volume
          persistentVolumeClaim:
            claimName: react-app-pvc


