apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: slave2  # Ensure it runs on slave2
      volumes:
        - name: react-volume
          persistentVolumeClaim:
            claimName: react-app-pvc
      initContainers:
        - name: init-app
          image: 'busybox'
          command:
            - /bin/sh
            - '-c'
            - |
              # Check if /app/src exists and is empty
              if [ ! -d /app/src ] || [ "$(ls -A /app/src)" ]; then
                echo "Setting up initial app directory";
                # Optionally copy any required initial files here
              fi
          volumeMounts:
            - mountPath: /app
              name: react-volume
      containers:
        - name: react-container
          image: 'node:latest'
          imagePullPolicy: Always
          command:
            - /bin/sh
            - '-c'
          args:
            - |
              npm install -g npm@10.9.0 && \
              cd /app && \
              if [ ! -f /app/src/App.js ]; then \
                npx create-react-app .; \
              fi && \
              npm start --host 0.0.0.0 --port 80  # Start the app on port 80
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: react-volume
      restartPolicy: Always
