apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: node:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: react-app-storage
            - name: config-volume
              mountPath: /etc/config  # Adjust the mount path as necessary
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: react-app-config
                  key: NODE_ENV
      volumes:
        - name: react-app-storage
          persistentVolumeClaim:
            claimName: react-app-pvc
        - name: config-volume
          configMap:
            name: react-app-config

