apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: node:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app  # This is where your code will be stored
              name: react-app-storage  # Name of the volume
          command: ["/bin/sh", "-c"]
          args:
            - npm install -g npm@10.9.0 && \
              npm install -g create-react-app && \
              npx create-react-app /app && \
              cd /app && \
              npm start --host 0.0.0.0 --port 80
      volumes:
        - name: react-app-storage
          persistentVolumeClaim:
            claimName: react-app-pvc  # Reference your PVC here


