apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: node:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              npm install -g npm@10.9.0 && \
              npm install -g create-vite && \
              mkdir -p /app && cd /app && \
              if [ ! -f package.json ]; then \
                echo "Creating new Vite app with React and TypeScript..."; \
                npm create vite@latest . -- --template react-ts && npm install axios express cors && npm install; \
              else \
                echo "/app directory exists. Installing dependencies..."; \
                npm install axios express cors; \
              fi && \
              chmod +x ./node_modules/.bin/vite && \
              npm run dev -- --host 192.168.0.162 --port 3000 & \
              ts-node /app/script.ts
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: react-volume
      nodeSelector:
        kubernetes.io/hostname: slave2
      volumes:
        - name: react-volume
          persistentVolumeClaim:
            claimName: react-app-pvc
