apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: 'node:latest'
          ports:
            - containerPort: 3000
          command: ["/bin/sh", "-c"]
          args: ["npm start"]
          volumeMounts:
            - name: react-volume
              mountPath: /app
      initContainers:
        - name: init-app
          image: 'node:latest'
          command:
            - /bin/sh
            - '-c'
          args:
            - |
              if [ ! -d /app/node_modules ]; then \
                echo "Installing dependencies..."; \
                cd /app && npm install; \
              fi && chmod -R 777 /app
          volumeMounts:
            - mountPath: /app
              name: react-volume
      volumes:
        - name: react-volume
          persistentVolumeClaim:
            claimName: react-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: node-js
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: react-app-pvc
  namespace: node-js
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

