apiVersion: v1
kind: PersistentVolume
metadata:
  name: react-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/worker2/app  # Adjust this path according to your node setup
