apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: react-app-pvc
  namespace: node-js
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # Make sure this matches the PV's storage class
