apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: node-js
spec:
  selector:
    app: react-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
    - name: api
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32062
  type: NodePort
